site_name: Помощник настройки production окружения
site_url: https://maximsamokhval.github.io/audit-checklist/
site_author: Maxim Samokhval

repo_name: maximsamokhval/audit-checklist
repo_url: https://github.com/maximsamokhval/audit-checklist
edit_uri: edit/main/docs

extra:
  generator: false
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/maksym_samokhval
    - icon: fontawesome/brands/github
      link: https://github.com/maximsamokhval

copyright: Copyright &copy; 2022 Maxim Samokhval

theme:
  name: material
  features:
    - toc.integrate
    - navigation.top
    - header.autohide
    - search.highlight

  palette:
    - scheme: default
      primary: orange
      accent: indigo
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: slate
      primary: orange
      accent: light blue
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
  language: ru
  font:
    text: Play
  icon:
    repo: fontawesome/brands/git
  plugins:
    - tags
    - social

markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html

nav:
  - Стартовая страница: index.md
  - MS SQL: MS SQL.md
  - 1С:Предприятие: Сервер 1С Предприятие.md
