site_name: Справочник. Настройки рабочего окружения
site_url: https://maximsamokhval.github.io/audit-checklist/
site_author: Maxim Samokhval
site_description: Сборник полезной информации по настройке рабочего окружения
repo_name: maximsamokhval/audit-checklist
repo_url: https://github.com/maximsamokhval/audit-checklist
edit_uri: edit/main/docs

extra:
  generator: false
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/maksym_samokhval
      name: Telegram me
    - icon: fontawesome/brands/github
      link: https://github.com/maximsamokhval

copyright: Copyright &copy; 2022 Maxim Samokhval

theme:
  name: material

  features:
    - toc.integrate
    - navigation.top
    #- navigation.tabs
    #- navigation.tabs.sticky
    - navigation.sections
    - navigation.instant
    - navigation.tracking
    #- navigation.expand
    - header.autohide
    - announce.dismiss
    - search.highlight
    - search.suggest
    - search.share

  palette:
    - scheme: default
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: slate
      primary: blue grey
      accent: deep orange
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
  language: ru
  font:
    text: Play
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/git
  plugins:
    #- tags
    - social

plugins:
  - rss
  - git-revision-date-localized
  - search:
      lang:
        - ru
        - en
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - md_in_html
  - def_list
  - footnotes
  - tables
  - meta
  - md_in_html
  - pymdownx.betterem
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.snippets
  - toc:
      permalink: true

nav:
  - Начало: index.md
  - SQL Docs:
      - MS SQL: SQL/MS SQL.md
      - PostgreSQL: SQL/PostgreSQL.md
      - lifehacks: SQL/lifehacks.md
  - 1С:Предприятие:
      - 1CServer/index.md
  - Windows:
      - Windows/index.md
  - Технологический журнал:
      - TechJournal/index.md
      - TechJournal/analyse.md
  - Заметки:
      - Notes/index.md
  - Про сайт:
      - about/index.md
